name: Python to EXE

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    # test if the commit message starts with a v
    # then test if the rest of the commits is a integer
    if: github.event.head_commit.message == '^v\\d+\\.\\d+\\.\\d+$'
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pygame librosa win11toast

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller ./main.py --noconfirm --onefile --windowed --name "Beat Down"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.commits.message }}
          release_name: "Beat Down ${{ github.event.commits.message }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/Beat Down.exe"