name: Python to EXE

on:
  push:
    tags: v*
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest
    if: ${{github.event.base_ref}} == "v*"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pygame librosa win11toast

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller ./main.py --noconfirm --onefile --windowed --name "Beat Down"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0  # Replace with your desired release version
          release_name: "Beat Down v1.0.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use 'RELEASE_TOKEN' if using a PAT

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: Beat Down.exe