name: Python to EXE

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Commit Message
        id: commit_message
        run: |
          echo "COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Generate Tag Name
        id: tag_name
        run: |
          # Clean up the commit message for a valid tag
          TAG_NAME="v$(echo $COMMIT_MSG | tr ' ' '-' | tr -cd '[:alnum:]-')"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
        env:
          COMMIT_MSG: ${{ env.COMMIT_MSG }}

      - name: Create Git Tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}
        env:
          TAG_NAME: ${{ env.TAG_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pygame librosa win11toast

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller ./main.py --noconfirm --onefile --windowed --name "Beat Down"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "Beat Down ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/Beat Down.exe"