name: test Python to EXE

on:
  push:
    tags: v*
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Extract Commit Message
        id: commit_message
        run: |
          echo "$(git log -1 --pretty=%B)" >> $env.COMMIT_MSG

      - name: Create Git Tag
        run: |
          git tag ${{ env.COMMIT_MSG }}
          git push origin ${{ env.COMMIT_MSG }}
        env:
          COMMIT_MSG: ${{ env.COMMIT_MSG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}